sudo: required
os: linux
language: ruby
rvm:
 - 2.6.1
 - jruby
install:
 - sudo apt-get install ruby-full build-essential zlib1g-dev
before_script:
 - echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
 - echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
 - echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
 - source ~/.bashrc
 - gem install jekyll bundler
 - source 'https://rubygems.org'
 - gem 'nokogiri'
 - gem 'rack', '~> 2.0.1'
 - gem 'rspec'
 - bundle install
script:
 - bundle exec jekyll build
