sudo: required
os: linux
language: ruby
rvm:
 - 2.6.1
 - jruby
install:
 - sudo apt-get install ruby-full build-essential zlib1g-dev
before_script:
 - echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
 - echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
 - echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
 - source ~/.bashrc
 - bundle config deployment 'true'
 - bundle install --jobs=3 --retry=3 
script:
 - bundle exec jekyll build
